<?php
	//CHIAVE DI VERIFICA PER SICUREZZA
	define('CHIAVE_MIA', 'MYSECURITYKEY');

	//WEB SERVICES
	define('WSDL', 'MYDNS/API/GFWs.asmx?WSDL');

	define('OFFSET_DAY_WS', '90');

	//Quante ore prima scatta la mail di secondo avviso
	define('ORE_PREAVVISO', '24'); 

	//DATABASE
	define('HOST', 'MYHOST');
	define('USER', 'MYUSER');
	define('PASSWORD', 'MYUSERPASSWORD');
	define('DATABASE', 'MYDATABASE');

?>
